export const CREDIT_NOTE_DETAIL_REQUEST = "CREDIT_NOTE_DETAIL_REQUEST";
export const CREDIT_NOTE_DETAIL_SUCCESS = "CREDIT_NOTE_DETAIL_SUCCESS";
export const CREDIT_NOTE_DETAIL_ERROR = "CREDIT_NOTE_DETAIL_ERROR";

export const CREDIT_NOTE_DELETE_REQUEST = "CREDIT_NOTE_DELETE_REQUEST";
export const CREDIT_NOTE_DELETE_SUCCESS = "CREDIT_NOTE_DELETE_SUCCESS";
export const CREDIT_NOTE_DELETE_ERROR = "CREDIT_NOTE_DELETE_ERROR";

export const DEBIT_DETAILS_REQUEST = "DEBIT_DETAILS_REQUEST";
export const DEBIT_DETAILS_SUCCESS = "DEBIT_DETAILS_SUCCESS";
export const DEBIT_DETAILS_ERROR = "DEBIT_DETAILS_ERROR";

export const DEBIT_NOTE_DELETE_REQUEST = "DEBIT_NOTE_DELETE_REQUEST";
export const DEBIT_NOTE_DELETE_SUCCESS = "DEBIT_NOTE_DELETE_SUCCESS";
export const DEBIT_NOTE_DELETE_ERROR = "DEBIT_NOTE_DELETE_ERROR";