export const SALE_DETAIL_REQUEST = "SALE_DETAIL_REQUEST";
export const SALE_DETAIL_SUCCESS = "SALE_DETAIL_SUCCESS";
export const SALE_DETAIL_ERROR = "SALE_DETAIL_ERROR";


export const SALEORDER_STATUS_REQUEST = "SALEORDER_STATUS_REQUEST";
export const SALEORDER_STATUS_SUCCESS = "SALEORDER_STATUS_SUCCESS";
export const SALEORDER_STATUS_ERROR = "SALEORDER_STATUS_ERROR";

export const SALEORDER_DELETE_REQUEST = "SALEORDER_DELETE_REQUEST";
export const SALEORDER_DELETE_SUCCESS = "SALEORDER_DELETE_SUCCESS";
export const SALEORDER_DELETE_ERROR = "SALEORDER_DELETE_ERROR";